# 30th April 2025

## Numpy

In [2]:
import numpy as np

In [3]:
np.__version__

'1.26.1'

In [4]:
import sys
sys.version

'3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)]'

# Creating a List

In [5]:
my_list = [0,1,2,3,4,5]
print(my_list)

[0, 1, 2, 3, 4, 5]


In [6]:
print(type(my_list))

<class 'list'>


# Creating an Array using List

In [9]:
np.array([my_list])

array([[0, 1, 2, 3, 4, 5]])

In [10]:
np.array(10)

array(10)

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [14]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [15]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
np.arange(20,10)  # first num < sec num

array([], dtype=int32)

In [19]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [20]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [23]:
ar =np.arange(30,20)   # 1st argg always < 2nd arg
ar

array([], dtype=int32)

In [24]:
np.arange(10,10)

array([], dtype=int32)

In [25]:
np.arange()

TypeError: arange() requires stop to be specified.

In [26]:
np.arange(1,10,5)

array([1, 6])

In [27]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [30]:
np.zeros(10)   # Parameter tuning

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.zeros(10, dtype=int)    # Hyperparameter tuning 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [33]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [34]:
np.array([my_list])

array([[0, 1, 2, 3, 4, 5]])

In [35]:
np.zeros((4,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [36]:
np.zeros((5,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [37]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [38]:
np.zeros((10,30),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [39]:
np.zeros((10,10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# ONE Functions

In [40]:
np.ones(3)

array([1., 1., 1.])

In [41]:
np.ones(3, dtype=int)

array([1, 1, 1])

In [42]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# 3 RAND Functions

In [44]:
np.ones(4)

array([1., 1., 1., 1.])

In [45]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [48]:
np.random.rand(3,2)

array([[0.53215214, 0.55113967],
       [0.01919176, 0.44031336],
       [0.56235325, 0.55182636]])

In [49]:
np.random.rand(5)

array([0.24715308, 0.64198416, 0.02278619, 0.6869118 , 0.86693751])

In [52]:
np.random.rand(3,5)

array([[0.84762806, 0.44238312, 0.52780289, 0.58573994, 0.93903461],
       [0.81864088, 0.62356401, 0.77740526, 0.45181751, 0.30339386],
       [0.53287994, 0.32679012, 0.58395963, 0.19686035, 0.61915998]])

In [55]:
np.random.randint(5)

3

In [58]:
np.random.randint(2,5)

2

In [59]:
np.random.randint(5,2)   # 1st arg < 2nd arg

ValueError: low >= high

In [60]:
np.random.randint(5,14)

11

In [61]:
np.random.randint(5,20,4,5)

TypeError: Cannot interpret '5' as a data type

In [62]:
np.random.randint(5,15,3)

array([ 7, 14,  9])

In [64]:
np.random.randint(5,10,(10,10))

array([[6, 6, 5, 8, 8, 6, 9, 6, 7, 9],
       [8, 7, 6, 6, 6, 5, 6, 9, 8, 7],
       [9, 8, 6, 9, 7, 7, 5, 7, 5, 7],
       [9, 5, 5, 5, 6, 9, 8, 5, 5, 5],
       [6, 7, 5, 8, 5, 8, 9, 8, 9, 8],
       [7, 9, 8, 5, 9, 9, 7, 7, 7, 8],
       [6, 9, 8, 7, 6, 5, 5, 7, 6, 8],
       [9, 5, 8, 9, 9, 9, 8, 8, 8, 8],
       [9, 5, 5, 6, 9, 8, 9, 7, 7, 8],
       [9, 8, 8, 7, 9, 8, 5, 5, 7, 8]])

In [65]:
np.random.randint(1,100,(12,12))

array([[18, 50, 53, 17, 84,  7, 79, 56, 56, 75, 79, 47],
       [47, 34, 13, 44, 81, 27, 35, 60, 50, 37, 80, 78],
       [77, 73, 66, 96, 22, 82, 93, 10, 31, 45, 38, 56],
       [45, 88, 35, 23, 25, 16, 72, 97, 97, 69,  5, 37],
       [35, 90, 47, 67, 91, 11, 61, 75, 50, 57, 64, 79],
       [89, 30, 91, 61, 12, 18, 44, 69, 96, 22, 54, 34],
       [37,  5, 87, 57, 14, 88, 50, 49, 78, 96, 76, 91],
       [24, 13, 51, 69, 75, 52, 87,  4, 43, 50, 92, 35],
       [65, 88, 96, 79, 61, 81, 86, 92, 50, 91, 48, 91],
       [ 9, 72, 13, 99, 51, 57, 29, 65, 53, 85,  4, 33],
       [19, 24, 46, 18, 49, 88, 28, 84, 76, 47,  5, 39],
       [31, 99, 93, 20, 42, 42, 11, 37, 90,  6, 65, 63]])

In [66]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [68]:
b = np.random.randint(10,20,(5,4))
b

array([[13, 13, 11, 17],
       [17, 19, 10, 17],
       [13, 17, 12, 12],
       [10, 19, 13, 11],
       [12, 14, 18, 16]])

# 01st May 2025

# Slicing in Matrix

In [4]:
import numpy as np
b = np.random.randint(10,20,(5,4))    # 5 rows & 4 columns between 10 to 20
print(b)

[[14 13 18 12]
 [11 12 18 16]
 [10 19 19 17]
 [18 15 17 11]
 [17 15 13 14]]


In [5]:
print(type(b))

<class 'numpy.ndarray'>


In [6]:
b

array([[14, 13, 18, 12],
       [11, 12, 18, 16],
       [10, 19, 19, 17],
       [18, 15, 17, 11],
       [17, 15, 13, 14]])

In [7]:
b[:]   # Slicing

array([[14, 13, 18, 12],
       [11, 12, 18, 16],
       [10, 19, 19, 17],
       [18, 15, 17, 11],
       [17, 15, 13, 14]])

In [11]:
b[2:6]   # print the rows 2nd row till 5th row

array([[10, 19, 19, 17],
       [18, 15, 17, 11],
       [17, 15, 13, 14]])

In [10]:
b[2,6]  # from the 2nd row print 6th column

16

In [13]:
b[1,-1]

16

In [14]:
b

array([[14, 13, 18, 12],
       [11, 12, 18, 16],
       [10, 19, 19, 17],
       [18, 15, 17, 11],
       [17, 15, 13, 14]])

In [18]:
b[2:3]

array([[10, 19, 19, 17]])

In [19]:
b[0:-2]

array([[14, 13, 18, 12],
       [11, 12, 18, 16],
       [10, 19, 19, 17]])

In [20]:
b

array([[14, 13, 18, 12],
       [11, 12, 18, 16],
       [10, 19, 19, 17],
       [18, 15, 17, 11],
       [17, 15, 13, 14]])

In [21]:
b[0,2]

18

In [22]:
b

array([[14, 13, 18, 12],
       [11, 12, 18, 16],
       [10, 19, 19, 17],
       [18, 15, 17, 11],
       [17, 15, 13, 14]])

In [23]:
b[-5,-3]

13

In [24]:
b[-4,2]

18

# Operations

In [27]:
a = np.random.randint(10,20,10)
a

array([17, 10, 15, 11, 10, 14, 11, 11, 12, 12])

In [28]:
id(a)

1685125318768

In [31]:
arr2 = np.random.randint(0,100,(10,10))
arr2

array([[75, 44, 77, 48,  4, 77, 94, 35, 42, 12],
       [66, 99, 36, 42, 95, 33, 94, 98,  9, 60],
       [38, 99, 34, 42, 69, 13, 93,  2, 32, 27],
       [23, 30, 37, 82, 49, 72, 10,  3, 49, 96],
       [80, 77, 85, 75, 36, 98, 65, 12, 36, 28],
       [ 6, 34, 35, 59,  5,  7,  0, 55, 42, 10],
       [27, 50, 25, 92, 43, 21, 53, 24, 70, 16],
       [54, 97, 74, 59,  0, 40, 41, 52, 13, 96],
       [21, 12, 45,  3, 59, 60, 57, 22, 93, 72],
       [22, 64, 78, 93, 49, 66, 27, 44, 78, 18]])

In [33]:
arr = [0,1,2,3,4,5]
np.array([arr])

array([[0, 1, 2, 3, 4, 5]])

In [34]:
arr[:]

[0, 1, 2, 3, 4, 5]

In [35]:
arr[:4]

[0, 1, 2, 3]

In [36]:
arr2

array([[75, 44, 77, 48,  4, 77, 94, 35, 42, 12],
       [66, 99, 36, 42, 95, 33, 94, 98,  9, 60],
       [38, 99, 34, 42, 69, 13, 93,  2, 32, 27],
       [23, 30, 37, 82, 49, 72, 10,  3, 49, 96],
       [80, 77, 85, 75, 36, 98, 65, 12, 36, 28],
       [ 6, 34, 35, 59,  5,  7,  0, 55, 42, 10],
       [27, 50, 25, 92, 43, 21, 53, 24, 70, 16],
       [54, 97, 74, 59,  0, 40, 41, 52, 13, 96],
       [21, 12, 45,  3, 59, 60, 57, 22, 93, 72],
       [22, 64, 78, 93, 49, 66, 27, 44, 78, 18]])

In [37]:
arr2[:]

array([[75, 44, 77, 48,  4, 77, 94, 35, 42, 12],
       [66, 99, 36, 42, 95, 33, 94, 98,  9, 60],
       [38, 99, 34, 42, 69, 13, 93,  2, 32, 27],
       [23, 30, 37, 82, 49, 72, 10,  3, 49, 96],
       [80, 77, 85, 75, 36, 98, 65, 12, 36, 28],
       [ 6, 34, 35, 59,  5,  7,  0, 55, 42, 10],
       [27, 50, 25, 92, 43, 21, 53, 24, 70, 16],
       [54, 97, 74, 59,  0, 40, 41, 52, 13, 96],
       [21, 12, 45,  3, 59, 60, 57, 22, 93, 72],
       [22, 64, 78, 93, 49, 66, 27, 44, 78, 18]])

In [38]:
arr2[0:5]

array([[75, 44, 77, 48,  4, 77, 94, 35, 42, 12],
       [66, 99, 36, 42, 95, 33, 94, 98,  9, 60],
       [38, 99, 34, 42, 69, 13, 93,  2, 32, 27],
       [23, 30, 37, 82, 49, 72, 10,  3, 49, 96],
       [80, 77, 85, 75, 36, 98, 65, 12, 36, 28]])

In [39]:
arr2[1,5]

33

In [40]:
arr2

array([[75, 44, 77, 48,  4, 77, 94, 35, 42, 12],
       [66, 99, 36, 42, 95, 33, 94, 98,  9, 60],
       [38, 99, 34, 42, 69, 13, 93,  2, 32, 27],
       [23, 30, 37, 82, 49, 72, 10,  3, 49, 96],
       [80, 77, 85, 75, 36, 98, 65, 12, 36, 28],
       [ 6, 34, 35, 59,  5,  7,  0, 55, 42, 10],
       [27, 50, 25, 92, 43, 21, 53, 24, 70, 16],
       [54, 97, 74, 59,  0, 40, 41, 52, 13, 96],
       [21, 12, 45,  3, 59, 60, 57, 22, 93, 72],
       [22, 64, 78, 93, 49, 66, 27, 44, 78, 18]])

In [41]:
arr2[-5,5]

7

In [42]:
arr2[-1,-2]

78

In [43]:
arr2[::-1]

array([[22, 64, 78, 93, 49, 66, 27, 44, 78, 18],
       [21, 12, 45,  3, 59, 60, 57, 22, 93, 72],
       [54, 97, 74, 59,  0, 40, 41, 52, 13, 96],
       [27, 50, 25, 92, 43, 21, 53, 24, 70, 16],
       [ 6, 34, 35, 59,  5,  7,  0, 55, 42, 10],
       [80, 77, 85, 75, 36, 98, 65, 12, 36, 28],
       [23, 30, 37, 82, 49, 72, 10,  3, 49, 96],
       [38, 99, 34, 42, 69, 13, 93,  2, 32, 27],
       [66, 99, 36, 42, 95, 33, 94, 98,  9, 60],
       [75, 44, 77, 48,  4, 77, 94, 35, 42, 12]])

In [44]:
arr2

array([[75, 44, 77, 48,  4, 77, 94, 35, 42, 12],
       [66, 99, 36, 42, 95, 33, 94, 98,  9, 60],
       [38, 99, 34, 42, 69, 13, 93,  2, 32, 27],
       [23, 30, 37, 82, 49, 72, 10,  3, 49, 96],
       [80, 77, 85, 75, 36, 98, 65, 12, 36, 28],
       [ 6, 34, 35, 59,  5,  7,  0, 55, 42, 10],
       [27, 50, 25, 92, 43, 21, 53, 24, 70, 16],
       [54, 97, 74, 59,  0, 40, 41, 52, 13, 96],
       [21, 12, 45,  3, 59, 60, 57, 22, 93, 72],
       [22, 64, 78, 93, 49, 66, 27, 44, 78, 18]])

In [45]:
arr2[::-2]

array([[22, 64, 78, 93, 49, 66, 27, 44, 78, 18],
       [54, 97, 74, 59,  0, 40, 41, 52, 13, 96],
       [ 6, 34, 35, 59,  5,  7,  0, 55, 42, 10],
       [23, 30, 37, 82, 49, 72, 10,  3, 49, 96],
       [66, 99, 36, 42, 95, 33, 94, 98,  9, 60]])

In [46]:
arr2[::-3]

array([[22, 64, 78, 93, 49, 66, 27, 44, 78, 18],
       [27, 50, 25, 92, 43, 21, 53, 24, 70, 16],
       [23, 30, 37, 82, 49, 72, 10,  3, 49, 96],
       [75, 44, 77, 48,  4, 77, 94, 35, 42, 12]])

In [50]:
np.array(arr)

array([0, 1, 2, 3, 4, 5])

In [55]:
arr2

array([[75, 44, 77, 48,  4, 77, 94, 35, 42, 12],
       [66, 99, 36, 42, 95, 33, 94, 98,  9, 60],
       [38, 99, 34, 42, 69, 13, 93,  2, 32, 27],
       [23, 30, 37, 82, 49, 72, 10,  3, 49, 96],
       [80, 77, 85, 75, 36, 98, 65, 12, 36, 28],
       [ 6, 34, 35, 59,  5,  7,  0, 55, 42, 10],
       [27, 50, 25, 92, 43, 21, 53, 24, 70, 16],
       [54, 97, 74, 59,  0, 40, 41, 52, 13, 96],
       [21, 12, 45,  3, 59, 60, 57, 22, 93, 72],
       [22, 64, 78, 93, 49, 66, 27, 44, 78, 18]])

In [56]:
arr2.max()

99

In [57]:
arr2.min()

0

In [60]:
np.array(arr)

array([0, 1, 2, 3, 4, 5])

In [62]:
arr2.mean()

48.15

In [63]:
arr2.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [66]:
from numpy import *
a = array([1,2,3,4,9])
median(a)

3.0

In [68]:
np.array(arr)

array([0, 1, 2, 3, 4, 5])

# Indexing

In [75]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [76]:
row = 4
col = 5

In [77]:
row

4

In [78]:
col

5

In [79]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [80]:
mat[row,col]

45

In [81]:
mat[4,5]

45

In [82]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [83]:
col = 6

In [84]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

## With Slices

In [85]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [86]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [87]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [88]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [89]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [90]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [91]:
row

4

In [92]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [93]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [94]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [95]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [96]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [97]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [98]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [99]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [100]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [101]:
mat[1,4]

14

In [102]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [103]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [104]:
mat[3,-3]

37

In [105]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [106]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [107]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [109]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [110]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [111]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [112]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [113]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [114]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [115]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [116]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [117]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [118]:
mat[::-2]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [119]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [120]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [121]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [122]:
mat[0,1]

1

In [123]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [124]:
mat[1:2,2:4]

array([[12, 13]])

In [126]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [127]:
mat[2:3,4:5]

array([[24]])

# Masking   
- Also called as Filter

In [128]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [129]:
id(mat)

1685127704144

In [130]:
mat < 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [131]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [132]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [133]:
mat[mat==50] 

array([50])

In [134]:
a1 = mat[mat<50] 
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [135]:
a2 = mat[mat>50] 
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [136]:
a3 = mat[mat>=50] 
a3

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [137]:
a4 = mat[mat==50]
a4

array([50])

In [138]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [139]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [140]:
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])